modLoader="javafml"
loaderVersion="[34,)"
license="GNU LGPLv3"
logoFile="logo.png"
displayURL="https://github.com/gdavid04/Phi"
authors="GDavid"
[[mods]]
modId="phi"
version="${file.jarVersion}"
displayName="Phi"
description='''
A Psi addon
'''
[[dependencies.phi]]
	modId="forge"
    mandatory=true
    versionRange="[36.2.20,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.phi]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
[[dependencies.phi]]
    modId="psi"
    mandatory=true
    versionRange="[1.16-95,)"
    ordering="AFTER"
    side="BOTH"
