name: Release
on:
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: JDK 1.8
      uses: actions/setup-java@v2
      with:
        distribution: adopt
        java-version: 8
    - name: Cache
      uses: actions/cache@v2
      with:
        path: ~/.gradle/caches
        key: ${{runner.os}}-gradle-${{hashFiles('build.gradle')}}
    - name: Gradle Build
      run: ./gradlew build
    - name: Get Release
      id: get_release
      uses: bruceadams/get-release@v1
      env:
        GITHUB_TOKEN: ${{github.token}}
    - name: Publish
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{github.token}}
      with:
        upload_url: ${{steps.get_release.outputs.upload_url}}
        asset_path: ./build/libs/phi-${{steps.get_release.outputs.tag_name}}.jar
        asset_name: Phi-${{steps.get_release.outputs.tag_name}}.jar
        asset_content_type: application/java-archive
